### ISSUE TITLE
Cannot set up with docker. | Database not seeding perhaps?

### ISSUE THREAD

**Issue by dillfrescott** [dahlia/hollo#57]
```
hollo-1          | 23:50:56.521 ERR fedify·federation·http: 'GET' '/': 500
postgres-1       | 2024-11-01 23:50:58.130 UTC [34] ERROR:  relation "credentials" does not exist at character 49
postgres-1       | 2024-11-01 23:50:58.130 UTC [34] STATEMENT:  select "email", "password_hash", "created" from "credentials" limit $1
hollo-1          | 783 |     query.execute()
hollo-1          | 784 |   }
hollo-1          | 785 |
hollo-1          | 786 |   function ErrorResponse(x) {
hollo-1          | 787 |     query && (query.cursorFn || query.describeFirst) && write(Sync)
hollo-1          | 788 |     const error = Errors.postgres(parseError(x))
hollo-1          |                                ^
hollo-1          | PostgresError: relation "credentials" does not exist
hollo-1          |  code: "42P01"
hollo-1          |
hollo-1          |       at ErrorResponse (/app/node_modules/postgres/src/connection.js:788:26)
hollo-1          |       at handle (/app/node_modules/postgres/src/connection.js:744:36)
hollo-1          |       at data (/app/node_modules/postgres/src/connection.js:478:9)
hollo-1          |       at emit (node:events:48:48)
hollo-1          |       at addChunk (node:stream:1731:22)
hollo-1          |       at readableAddChunk (node:stream:1686:30)
hollo-1          |       at data (node:net:44:9)
hollo-1          |
hollo-1          | 23:50:58.130 ERR fedify·federation·http: 'GET' '/': 500
```

My docker compose with passwords omitted:

```
services:
  hollo:
    image: ghcr.io/dahlia/hollo:latest
    ports:
    - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/database"
      SECRET_KEY: "actual secret key"
      LOG_LEVEL: "info"
      BEHIND_PROXY: "true"
      S3_REGION: us-east-1
      S3_BUCKET: hollo
      S3_URL_BASE: http://localhost:9000/hollo/
      S3_ENDPOINT_URL: http://minio:9000
      S3_FORCE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
    - postgres
    - minio
    - create-bucket
    restart: always

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
    - ./minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  create-bucket:
    image: minio/mc:RELEASE.2024-09-16T17-43-14Z
    depends_on:
    - minio
    entrypoint: |
      /bin/sh -c "
        /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb minio/hollo;
        /usr/bin/mc anonymous set public minio/hollo;
        exit 0;
      "
 ```
